<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="RTZ 2 (зима)">
<General productName="Vugen" productVer="2020" os="" host="DESKTOP-UHCG7Q0"><DocLocation><![CDATA[C:\Users\Admin\Desktop\LoadRunner (НТ Стажировка)\WebTour_part2_(ABGAR)_Task1_21.04_(Kovaleko V)]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V)]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Action0]]></AName>
<Summary sTime="11.11.2020 - 13:40:47" eTime="11.11.2020 - 13:40:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Action0 Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:50]]></Time>
<TimeTick>1605091250</TimeTick>
<NodeArgs eType="General" icon="4" nRep="9" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:50]]></Time>
<TimeTick>1605091250</TimeTick>
<NodeArgs eType="General" icon="1" nRep="10" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:40:48" eTime="11.11.2020 - 13:40:50" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T7" iterID="2" >
<Action rID="T8">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:52]]></Time>
<TimeTick>1605091252</TimeTick>
<NodeArgs eType="General" icon="4" nRep="15" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:52]]></Time>
<TimeTick>1605091252</TimeTick>
<NodeArgs eType="General" icon="1" nRep="16" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:40:50" eTime="11.11.2020 - 13:40:52" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="14" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="13" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T11" iterID="3" >
<Action rID="T12">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:54]]></Time>
<TimeTick>1605091254</TimeTick>
<NodeArgs eType="General" icon="4" nRep="21" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration3\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:54]]></Time>
<TimeTick>1605091254</TimeTick>
<NodeArgs eType="General" icon="1" nRep="22" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:40:52" eTime="11.11.2020 - 13:40:54" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="20" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="19" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T15" iterID="4" >
<Action rID="T16">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:56]]></Time>
<TimeTick>1605091256</TimeTick>
<NodeArgs eType="General" icon="4" nRep="27" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:56]]></Time>
<TimeTick>1605091256</TimeTick>
<NodeArgs eType="General" icon="1" nRep="28" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:40:54" eTime="11.11.2020 - 13:40:56" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="26" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="25" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T19" iterID="5" >
<Action rID="T20">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:58]]></Time>
<TimeTick>1605091258</TimeTick>
<NodeArgs eType="General" icon="4" nRep="33" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration5\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:40:58]]></Time>
<TimeTick>1605091258</TimeTick>
<NodeArgs eType="General" icon="1" nRep="34" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:40:56" eTime="11.11.2020 - 13:40:58" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="32" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="31" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T23" iterID="6" >
<Action rID="T24">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:00]]></Time>
<TimeTick>1605091260</TimeTick>
<NodeArgs eType="General" icon="4" nRep="39" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration6\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:00]]></Time>
<TimeTick>1605091260</TimeTick>
<NodeArgs eType="General" icon="1" nRep="40" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:40:58" eTime="11.11.2020 - 13:41:00" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="38" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="37" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 6 (Row 6)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T27" iterID="7" >
<Action rID="T28">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:02]]></Time>
<TimeTick>1605091262</TimeTick>
<NodeArgs eType="General" icon="4" nRep="45" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration7\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:02]]></Time>
<TimeTick>1605091262</TimeTick>
<NodeArgs eType="General" icon="1" nRep="46" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:41:00" eTime="11.11.2020 - 13:41:02" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="44" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="43" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 7 (Row 7)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T31" iterID="8" >
<Action rID="T32">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:04]]></Time>
<TimeTick>1605091264</TimeTick>
<NodeArgs eType="General" icon="4" nRep="51" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration8\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:04]]></Time>
<TimeTick>1605091264</TimeTick>
<NodeArgs eType="General" icon="1" nRep="52" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:41:02" eTime="11.11.2020 - 13:41:04" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="50" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="49" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 8 (Row 8)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T35" iterID="9" >
<Action rID="T36">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:06]]></Time>
<TimeTick>1605091266</TimeTick>
<NodeArgs eType="General" icon="4" nRep="57" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration9\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:06]]></Time>
<TimeTick>1605091266</TimeTick>
<NodeArgs eType="General" icon="1" nRep="58" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:41:04" eTime="11.11.2020 - 13:41:06" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="56" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="55" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 9 (Row 9)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T39" iterID="10" >
<Action rID="T40">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Url: Webtours]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Step failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:09]]></Time>
<TimeTick>1605091269</TimeTick>
<NodeArgs eType="General" icon="4" nRep="63" status="Failed" >
<Disp><![CDATA[Url: Webtours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration10\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[11.11.2020 - 13:41:09]]></Time>
<TimeTick>1605091269</TimeTick>
<NodeArgs eType="General" icon="1" nRep="64" status="Failed" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11.11.2020 - 13:41:06" eTime="11.11.2020 - 13:41:09" passed="0" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="62" status="Failed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="61" status="Failed" >
<Disp><![CDATA[WebTour_part2_Task1_21.04_(Kovaleko V) Iteration 10 (Row 10)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T43">
<AName><![CDATA[Actionend]]></AName>
<Summary sTime="11.11.2020 - 13:41:09" eTime="11.11.2020 - 13:41:09" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="67" >
<Disp><![CDATA[Actionend Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="11.11.2020 - 13:40:47" eTime="11.11.2020 - 13:41:09" passed="0" failed="20" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Failed" >
<Disp><![CDATA[Test WebTour_part2_Task1_21.04_(Kovaleko V) Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>